<?php
namespace Ringo\Bundle\PhpRedmonBundle\Tests\Model;

use Ringo\Bundle\PhpRedmonBundle\Model\Database;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-06 at 22:05:35.
 */
class DatabaseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Database();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Database::getId
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Database::setId
     */
    public function testGetId()
    {
        $this->assertNull($this->object->getId());
        $this->object->setId(1);
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Database::getName
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Database::setName
     */
    public function testGetName()
    {
        $this->assertNull($this->object->getName());
        $this->object->setName("test");
        $this->assertEquals("test", $this->object->getName());
    }
}
