<?php

use Ringo\Bundle\PhpRedmonBundle\Model\Log;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-06 at 22:06:02.
 */
class LogTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Log
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Log();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::getId
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::setId
     */
    public function testGetId()
    {
        $this->assertEmpty($this->object->getId());
        $this->object->setId(2);
        $this->assertEquals(2, $this->object->getId());
    }

    /**
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::getCreatedAt
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::setCreatedAt
     */
    public function testGetCreatedAt()
    {
        $date = new \DateTime();
        $this->assertNull($this->object->getCreatedAt());
        $this->object->setCreatedAt($date);
        $this->assertEquals($date, $this->object->getCreatedAt());
        $this->assertEquals($date->getTimestamp(), $this->object->getId());
    }

    /**
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::getDatas
     * @covers Ringo\Bundle\PhpRedmonBundle\Model\Log::setDatas
     * @todo   Implement testGetDatas().
     */
    public function testGetDatas()
    {
        $datas = array('some datas', 'and others');
        $this->assertEmpty($this->object->getDatas());
        $this->object->setDatas($datas);
        $this->assertEquals($datas, $this->object->getDatas());
    }
}
